### ISSUE TITLE
The GPT-4 generated dataset

### ISSUE THREAD

**Issue by rongtongxueya** [mayug/VDT-Adapter#1]
Excellent work, and thank you very much for sharing the code and the data generated by GPT.I’m keenly interested in understanding how you processed the data in your 'gpt4_date'. Would you be so kind as to explain the methodology? I‘m eager to apply a similar approach to my own data

**Comment by chris-vorster** [comment]
Hi @rongtongxueya 

Please see _Section 2: Prompts for GPT-4_ in our Supplementary. We specified how the LLM output should be structured in the prompt, for example: "Return the answer as a python dictionary with the object name as the key and the value is a list of sentences.".

If you have any specific questions, feel free to ask.
